# action.yml
name: 'Custom Github Action'
decription: 'GA take inputs and returns outputs'
inputs:
  num:
    required: true
    default: "1"
  outputs:
    num_squared:
      value: ${{ steps.get-square.outputs.num_squared }}
   runs:
    
